export const UPDATE_WEATHER = 'UPDATE_WEATHER';
export const UPDATE_WEATHER_LIST = 'UPDATE_WEATHER_LIST';
export const REMOVE_FROM_UPDATE = 'REMOVE_FROM_UPDATE';
export const REMOVE_FROM_UPDATE_LIST = 'REMOVE_FROM_UPDATE_LIST';
export const ADD_TO_UPDATE_LIST = 'ADD_TO_UPDATE_LIST';